Repository swe-ms-boun/2018fall-swe574-g1, pull requests merged in 2018-11, with the labels that each got.

#78 Feature/taneresme/common ui features
  src/main/java/com/boun/swe/mnemosyne/config/WebSecurityConfig.java
  src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  src/main/java/com/boun/swe/mnemosyne/service/SecurityService.java
  src/main/java/com/boun/swe/mnemosyne/service/UserDetailsServiceImpl.java
  src/main/resources/static/css/bootstrap.css
  src/main/resources/static/css/custom.css
  src/main/resources/static/css/docs.css
  src/main/resources/static/css/font-awesome.css
  src/main/resources/static/fonts/FontAwesome.otf
  src/main/resources/static/fonts/fontawesome-webfont.eot
  src/main/resources/static/fonts/fontawesome-webfont.svg
  src/main/resources/static/fonts/fontawesome-webfont.ttf
  src/main/resources/static/fonts/fontawesome-webfont.woff
  src/main/resources/static/fonts/fontawesome-webfont.woff2
  src/main/resources/static/js/bootstrap.js
  src/main/resources/static/js/custom.js
  src/main/resources/static/js/docs.js
  src/main/resources/templates/fragments/commons.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/welcome.html
Labels: tier.ui, type.feature

#82 login process completed
  src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  src/main/java/com/boun/swe/mnemosyne/service/SecurityService.java
  src/main/resources/templates/login.html
Labels: tier.ui, type.bug

#86 Add add memory Change login and register
  src/main/java/com/boun/swe/mnemosyne/config/WebSecurityConfig.java
  src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  src/main/resources/static/css/memory.css
  src/main/resources/static/css/onepage-scroll.css
  src/main/resources/static/js/addmemory.js
  src/main/resources/static/js/iterative.js
  src/main/resources/static/js/onepagescroll.js
  src/main/resources/templates/addmemory.html
  src/main/resources/templates/fragments/commons.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
Labels: tier.ui, type.enhancement

#88 Add memory endpoints
  src/main/java/com/boun/swe/mnemosyne/config/WebSecurityConfig.java
  src/main/java/com/boun/swe/mnemosyne/controller/MemoryController.java
  src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  src/main/java/com/boun/swe/mnemosyne/exception/MemoryNotFoundException.java
  src/main/java/com/boun/swe/mnemosyne/model/Location.java
  src/main/java/com/boun/swe/mnemosyne/model/Memory.java
  src/main/java/com/boun/swe/mnemosyne/repository/MemoryRepository.java
  src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
  src/main/java/com/boun/swe/mnemosyne/validator/MemoryValidator.java
  src/main/resources/templates/memories.html
Labels: priority.high, tier.api, type.design

#97 Feature/tugcan/ui improvements
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
  mnemosyne/src/main/resources/application.properties
  mnemosyne/src/main/resources/static/css/memory.css
  mnemosyne/src/main/resources/static/js/addmemory.js
  mnemosyne/src/main/resources/static/js/custom.js
  mnemosyne/src/main/resources/static/js/onepagescroll.js
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/index.html
  mnemosyne/src/main/resources/templates/login.html
  mnemosyne/src/main/resources/templates/memories.html
  mnemosyne/src/main/resources/templates/register.html
  mnemosyne/src/main/resources/templates/welcome.html
Labels: module.map, review.pending, tier.ui, type.enhancement, type.feature
