Repository swe-ms-boun/2018fall-swe574-g1, pull requests merged in 2018-12, with the labels that each got.

#100 Feature/taneresme/ui modifications
  .travis.yml
  README.md
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/WebSecurityConfig.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  mnemosyne/src/main/resources/templates/fragments/header.html
  mnemosyne/src/main/resources/templates/login.html
  mnemosyne/src/main/resources/templates/register.html
Labels: priority.high, tier.ui, type.enhancement

#111 Feature/taneresme/ui modifications
  .travis.yml
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/WebSecurityConfig.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/HomeController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/SecurityService.java
  mnemosyne/src/main/resources/static/css/custom.css
  mnemosyne/src/main/resources/static/css/docs.css
  mnemosyne/src/main/resources/static/css/memory.css
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/fragments/header.html
  mnemosyne/src/main/resources/templates/home.html
  mnemosyne/src/main/resources/templates/login.html
  mnemosyne/src/main/resources/templates/register.html
Labels: tier.ui, type.feature

#115 new memory path in the header fixed, memory and friendship removed fr…
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/WebSecurityConfig.java
  mnemosyne/src/main/resources/templates/fragments/header.html
  mnemosyne/src/main/resources/templates/home.html
  mnemosyne/src/main/resources/templates/index.html
  mnemosyne/src/main/resources/templates/profile.html
  mnemosyne/src/main/resources/templates/welcome.html
Labels: tier.ui, type.fix

#117 Memory addition, home page iteration, memory view
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/DataLoader.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/MemoryController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/Memory.java
  mnemosyne/src/main/resources/static/css/memory-view.css
  mnemosyne/src/main/resources/static/js/addmemory.js
  mnemosyne/src/main/resources/static/js/annotator.js
  mnemosyne/src/main/resources/static/js/custom.js
  mnemosyne/src/main/resources/templates/home.html
  mnemosyne/src/main/resources/templates/memories.html
  mnemosyne/src/main/resources/templates/memory_view.html
Labels: priority.high, review.approved, tier.api, tier.ui, type.annotation, type.design, type.enhancement, type.feature

#120 Feature/vedat/support postgres
  annotation-service/src/main/resources/application.properties
  annotation-service/src/main/resources/application.yml
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/DataLoader.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/MemoryController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ProfileController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/Location.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/Memory.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/User.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
  mnemosyne/src/main/resources/application.properties
  mnemosyne/src/main/resources/application.yml
Labels: priority.high, tier.db, type.enhancement

#121 hardcoded profile name resolved
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/UserController.java
  mnemosyne/src/main/resources/templates/profile.html
Labels: tier.ui, type.fix

#125 acquiring total number of memories functionality implemented
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
Labels: tier.api, type.feature
