Repository swe-ms-boun/2018fall-swe574-g1, pull requests merged in 2019-01, with the labels that each got.

#137 Feature/taneresme/memory thumbnail
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/DataLoader.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/MemoryController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ProfileController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/SocialController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/Memory.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/User.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/UserService.java
  mnemosyne/src/main/resources/static/css/custom.css
  mnemosyne/src/main/resources/static/js/custom.js
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/fragments/header.html
  mnemosyne/src/main/resources/templates/home.html
  mnemosyne/src/main/resources/templates/profile.html
Labels: tier.api, tier.db, tier.ui, type.enhancement, type.feature, type.fix

#138 Feature/ugurcan/uiimprovements
  mnemosyne/pom.xml
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/model/Location.java
  mnemosyne/src/main/resources/static/js/custom.js
  mnemosyne/src/main/resources/templates/index.html
  mnemosyne/src/main/resources/templates/memory_view.html
Labels: tier.api, tier.ui, type.feature, type.map

#139 memory_view page modified. Applied bootstrap...
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/resources/static/css/memory.css
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/memory_view.html
Labels: tier.ui

#140 maps centered for first marker
  mnemosyne/src/main/resources/static/js/custom.js
Labels: tier.ui, type.feature

#143 Add annotation for both text and images
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/config/DataLoader.java
  mnemosyne/src/main/resources/static/js/custom.js
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/memory_view.html
Labels: priority.high, tier.ui

#141 index page modified...
  mnemosyne/src/main/resources/templates/index.html
Labels: tier.ui

#144 Fix user assign to body
  mnemosyne/src/main/resources/static/js/custom.js
Labels: type.fix

#145 Displaying memories from html and as a thumbnail were implemented.
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ProfileController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/memory_view.html
Labels: tier.api, tier.ui, type.feature

#146 Added last 10 memory on the index page and dome bug fixes implemented…
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/repository/MemoryRepository.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
  mnemosyne/src/main/resources/templates/fragments/commons.html
  mnemosyne/src/main/resources/templates/index.html
Labels: tier.ui, type.feature

#142 Feature/vedat/cors config
  annotation-service/src/main/java/com/boun/swe/mnemosyne/annotation/annotationservice/config/CorsConfig.java
  annotation-service/src/main/java/com/boun/swe/mnemosyne/annotation/annotationservice/model/Target.java
  annotation-service/src/main/java/com/boun/swe/mnemosyne/annotation/annotationservice/repository/AnnotationRepository.java
  annotation-service/src/main/resources/application.yml
  annotation-service/src/test/java/com/boun/swe/mnemosyne/annotation/annotationservice/controller/AnnotationValidatorTest.java
  annotation-service/src/test/java/com/boun/swe/mnemosyne/annotation/annotationservice/model/AnnotationTest.java
  annotation-service/src/test/java/com/boun/swe/mnemosyne/annotation/annotationservice/service/AnnotationServiceTest.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/SocialController.java
  mnemosyne/src/main/resources/application-deployment.yml
  mnemosyne/src/main/resources/application.yml
Labels: module.annotation, tier.api, tier.db, type.enhancement

#147 annotations count added in index page
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/Application.java
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/controller/ViewController.java
  mnemosyne/src/main/resources/templates/index.html
Labels: tier.ui, type.annotation

#148 fixed null pointer exception in memoryService.
  mnemosyne/src/main/java/com/boun/swe/mnemosyne/service/MemoryService.java
Labels: tier.api, type.fix

#149 sequence diagrams and visio file added
  docs/create-annotation-sequence.png
  docs/create-memory-sequence.png
  docs/get-memory-sequence.png
  docs/project.drawings.vsdx
Labels: type.document

#150 Fix image upload problem
  mnemosyne/src/main/resources/static/js/addmemory.js
Labels: tier.ui, type.fix
